resolver: lts-18.28

flags:
  liquid-fixpoint:
    devel: true

packages:
  - "."

extra-deps:
  - hashable-1.3.5.0
  - git: https://github.com/ConnorBaker/rest
    commit: 28890b264fde96bed89935d6f10a3acc203ab846

nix:
  enable: true
  pure: true
  packages: [cacert z3]
