resolver: lts-18.28

packages:
  - "."

extra-deps:
  - hashable-1.3.5.0
  - git: https://github.com/ConnorBaker/rest
    commit: eb12a7107ec98e2b06cf33777479148514aff4ce

nix:
  enable: true
  pure: true
  packages:
    - cacert
    - z3
