resolver: lts-18.28

flags:
  liquid-fixpoint:
    devel: true

packages:
  - "."

extra-deps:
  - hashable-1.3.5.0
  - git: https://github.com/ConnorBaker/rest
    commit: e386966671b6f6faa6c6cd95a9135040e978cd5d

nix:
  enable: true
  pure: true
  packages:
    - cacert
    - z3
