name: Continuous integration
on:
  push:
  workflow_dispatch:

env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.LIQUID_FIXPOINT_WORKFLOW_TOKEN }}
            experimental-features = nix-command flakes
      - name: Mount dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: cabal-cache-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('cabal.project.freeze') }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            cabal-cache-${{ runner.os }}-${{ env.cache-version }}-
            cabal-cache-${{ runner.os }}-

      - name: Setup
        run: nix develop --command -- cabal update
      - name: Build
        run: nix develop --command -- cabal build --enable-tests
      - name: Test (test)
        run: nix develop --command -- cabal test test --test-show-details=direct
      - name: Test (tasty)
        run: nix develop --command -- cabal test tasty --test-show-details=direct
