name: Continuous integration
on: [push]
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  tests:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.LIQUID_FIXPOINT_WORKFLOW_TOKEN }}
            experimental-features = nix-command flakes
      - name: Mount dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-cache-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('flake.lock') }}
      - name: Setup
        run: nix develop --command -- stack setup --verbose
      - name: Build
        run: nix develop --command -- stack build --pedantic --verbose
      - name: Test
        run: nix develop --command -- stack test --pedantic --verbose
